#!/usr/bin/env python3
"""
main.py

Main Script for Camera Vision and Detection System

This script runs the full camera vision and detection subsystem in this order:

1. Run system_check.py
   - Verifies that the Raspberry Pi hotspot is active
   - Verifies that the ESP32-CAM is connected
   - Verifies that the ESP32-CAM web server is responding
   - Verifies that the laptop is also connected to the hotspot

2. Run camera_capture.py
   - Configures the ESP32-CAM settings
   - Opens the camera stream
   - Waits for the user to press ENTER
   - Captures and saves image to the Raspberry Pi

3. Run detection.py
   - Loads the saved image
   - Detects the center of each bolt
   - Converts pixel coordinates into real-world coordinates (in mm)
   - Saves the JSON, TXT, and debug image outputs

This file imports the main function from each script and runs them in sequence.
If one script fails to run correctly, the script stops immediately and the following stage does not run

"""

import sys
import time

# Import the main callable function from scripts system_check.py, camera_capture.py, and detection.py
from system_check import run_system_check
from camera_capture import run_capture
from detection import run as run_detection

# Printing titles of each script being called in the main function, for better readability in the terminal's output
def print_section_title(title):
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70 + "\n")

# Running the full camera vision system in order
def main():
    """
    Runs scripts in this order:
    Step 1: Run the system check
    Step 2: Capture an image
    Step 3: Run bolt detection

    - If the system check fails, the system stops.
    - If image capture fails, the system stops.
    - If detection fails, the system stops.
    - If all steps succeed, the full system is considered completed.

    """
    # -------------------------------------------------------------------------
    # INTRODUCTION TO CAMERA VISION AND DETECTION SUBSYSTEM
    # -------------------------------------------------------------------------
    # Printing statements for user understandability
    print_section_title("CAMERA VISION AND DETECTION SUBSYSTEM")

    print("This script will run the complete workflow in order:")
    print("1. System check")
    print("2. Camera capture")
    print("3. Bolt detection")
    print("\nIf any stage fails, the system will stop.\n")

    # Pausing to make the output easier to follow
    time.sleep(5)
    # -------------------------------------------------------------------------
    # STEP 1: system_check.py
    # -------------------------------------------------------------------------
    # Beginning by verifying that the hotspot, ESP32-CAM, web server, and laptop connections are all correct
    print_section_title("STEP 1: Running system_check.py")

    system_ok = run_system_check()

    # If the system check fails, system stops immediately
    if not system_ok:
        print("[ERROR] Main system stopped because system check failed.")
        return False

    print("[OK] System check completed successfully!")
    time.sleep(5)

    # -------------------------------------------------------------------------
    # STEP 2: camera_capture.py
    # -------------------------------------------------------------------------
    # Capturing an image using the ESP32-CAM
    print_section_title("STEP 2: Running camera_capture.py")

    captured_image_path = run_capture()

    # If the camera capture fails, system stops immediately
    if not captured_image_path:
        print("[ERROR] Main system stopped because image capture failed.")
        return False

    print(f"[OK] Image capture completed successfully!")
    print(f"[INFO] Captured image path: {captured_image_path}")
    time.sleep(5)

    # -------------------------------------------------------------------------
    # STEP 3: detection.py
    # -------------------------------------------------------------------------
    # Loading the captured image and performing bolt detection
    print_section_title("STEP 3: Running detection.py")

    detection_ok = run_detection()

    # If detection fails, system stops immediately
    if not detection_ok:
        print("[ERROR] Main system stopped because bolt detection failed.")
        return False

    print("[OK] Bolt detection completed successfully!")
    time.sleep(5)

    # -------------------------------------------------------------------------
    # FINAL MESSAGE FOR USER
    # -------------------------------------------------------------------------
    # If the code reaches this point, then all three scripts have succeeded
    print_section_title("CAMERA VISION AND DETECTION COMPLETED SUCCESSFULLY!")
    print("Output files generated by detection.py are now available:")
    print("- lug_coordinates.json")
    print("- lug_coordinates.txt")
    print("- debug_detection.jpg")

    return True

if __name__ == "__main__":
    """
    Runs the main function, which runs system_check.py, camera_capture.py, and detection.py in order

    Exit codes:
    Returns 0 if successful
    Returns 1 if failure

    """
    success = main()
    sys.exit(0 if success else 1)